/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'my friend pedro - blood bullets bananas_0000026384D30000.bin'
*/

/* 10 */
struct __unaligned __declspec(align(2)) struct_this
{
  _QWORD qword0;
  _BYTE gap8[16];
  _QWORD qword18;
  _QWORD qword20;
  _QWORD qword28;
  _BYTE gap30[8];
  struct_levelTimers *levelTimers;
  struct_root *root;
  struct_rootShared *rootShared;
  _QWORD qword50;
  unsigned __int8 levelEndedDoOnce;
  _BYTE showUITimerDoOnce;
};

/* 11 */
struct struct_rootShared
{
  _BYTE gap0[142];
  _BYTE showUITimer;
};

/* 12 */
struct __declspec(align(8)) struct_root
{
  struct_data *vtable;
  _BYTE gap8[1906];
  _BYTE fadeToBlack;
  _BYTE gap77B[155];
  unsigned __int8 unsigned___int8816;
  _BYTE gap817[85];
  float startTime;
  float finishTime;
  float timePaused;
};

/* 13 */
struct struct_data
{
  _BYTE gap0[760];
  unsigned int (__fastcall *pfunc2F8)(struct_root *);
};

/* 14 */
struct __unaligned __declspec(align(4)) struct_levelTimers
{
  _QWORD *vftable;
  _BYTE gap8[16];
  _DWORD dword18;
};